### ISSUE TITLE
[sota] study most promising algorithms

### ISSUE THREAD

**Issue by mox601** [Cybion-Italy/socialeyeser#2]
from http://www.crcnetbase.com/doi/book/10.1201/EBK1439826119

**Comment by sergiodaia** [comment]
One of the promising trend detection algorithm seems to be the ADWIN mostly because a java implementation has been found: http://downloads.sourceforge.net/project/adaptive-mining/ADWIN_Java.zip?r=http%3A%2F%2Fsourceforge.net%2Fp%2Fadaptive-mining%2Fwiki%2FHome%2F&ts=1400490774&use_mirror=freefr

It works well with stationary streams that have significant change. 
Unfortunately this can't be applied to twitter streams due to the non stationary nature of twitter streams. In order to be useful it is highly suggested to approach the problem with ensemble methods combining multiple adwins (one for feature) in a high level trend detector which would have a broader view on the underlaying stream. This leads to the definition of a new component and it's internal logic.

A parallel solution might be using histograms for different periods of time for each interesting feature and then apply the chi-square test
